### ISSUE TITLE
Help needed!

### ISSUE THREAD

**Issue by msonowal** [arleslie/2checkout#2]
Dude can you give a help or documenteation or guide for how to integrate your package in laravel 5

**Comment by arleslie** [comment]
Hello @msonowal currently this project is a work in progress.
However you can use it if you'd like.

`composer require arleslie/2checkout`

Then add the service provider (`arleslie\TwoCheckout\ServiceProvider`) to your laravel config and if you want to use the facade map the alias `TwoCheckout` to `arleslie\TwoCheckout\Facade`.

To use the facade you'll need to add the config file from the publish directory.

From there you can call `TwoCheckout::payment()->createSale([])` to create a sale. 
See the documentation at https://www.2checkout.com/documentation/payment-api/create-sale for what arguments to provide in the array.

You can also just call the class by:

```
use arleslie\TwoCheckout\Base as TwoCheckout;

$twocheckout = new TwoCheckout(<user>, <pass>, <privateKey>, <sellerId>);
$twocheckout->account()->getPayments(); // Returns all payments.
```

**Comment by arleslie** [comment]
I updated the readme to provide general installation steps.
Quite a bit of the API calls are still missing but any that accept parameters should be pulled from 2checkout's API docs.
